version: "3"
services:
  db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: cineshaven
      MYSQL_USER: root123
      MYSQL_PASSWORD: root123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    expose:
      - 3307
    volumes:
      - ./dumpSQL:/docker-entrypoint-initdb.d
      - /mysql/home:/docker-entrypoint-initdb.d
    #command: --init-file /docker-entrypoint-initdb.d/dumpPFG.sql

  backend:
    container_name: springbackend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: sh -c 'bash /app/wait-for-it.sh db:3306 -t 60 -- java -jar target/PFG_haven-0.0.1-SNAPSHOT.jar'

  frontend:
    container_name: vuefrontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
