version: '3'
services:
  db:
    container_name: db
    image: mysql:8.0
    hostname: VIP
    environment:
      MYSQL_DATABASE: cineshaven
      MYSQL_USER: root123
      MYSQL_PASSWORD: root123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    expose:
      - 3307
    volumes:
      - ./dumpPFG.sql:/docker-entrypoint-initcinesDB.d/dumpPFG.sql
    command: --init-file /docker-entrypoint-initcinesDB.d/dumpPFG.sql
  
  backend:
    container_name: springbackend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: sh -c 'bash /app/wait-for-it.sh db:3306 -t 30 -- java -jar target/PFG_haven-0.0.1-SNAPSHOT.jar'

  frontend:
    container_name: vuefrontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8081:5173"
    depends_on:
      - backend
